"use client";

import React, { useState, useEffect } from "react";
import NavBar from "@/components/layout/NavBar";
import { getValidationReport, getValidationHistory, getValidationReportByTimestamp } from "@/lib/api";

const BADGE_COLORS: Record<string, { bg: string, text: string }> = {
  PASS: { bg: "rgba(22, 163, 74, 0.1)", text: "var(--green)" },
  WARNING: { bg: "rgba(202, 138, 4, 0.1)", text: "#ca8a04" },
  FAIL: { bg: "rgba(220, 38, 38, 0.1)", text: "var(--red)" }
};

export default function AdminPage() {
  const [report, setReport] = useState<any>(null);
  const [history, setHistory] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadDashboard = async () => {
    setLoading(true);
    setError(null);
    try {
      const [reportData, historyData] = await Promise.all([
        getValidationReport(),
        getValidationHistory().catch(() => [])
      ]);
      setReport(reportData);
      setHistory(historyData);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to retrieve pipeline audit reports.");
    } finally {
      setLoading(false);
    }
  };

  const loadHistoricalReport = async (timestamp: string) => {
    setLoading(true);
    setError(null);
    try {
      const data = await getValidationReportByTimestamp(timestamp);
      setReport(data);
    } catch (err: any) {
      console.error(err);
      setError(err.message || `Failed to load report for timestamp: ${timestamp}`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadDashboard();
  }, []);

  const getStatusBadge = (status: string) => {
    const style = BADGE_COLORS[status] || { bg: "rgba(0,0,0,0.05)", text: "var(--grey3)" };
    return (
      <span
        style={{
          background: style.bg,
          color: style.text,
          padding: "4px 10px",
          borderRadius: "8px",
          fontWeight: 700,
          fontSize: "10px",
          textTransform: "uppercase",
          letterSpacing: "0.05em",
        }}
      >
        {status}
      </span>
    );
  };

  const getScoreColor = (score: number) => {
    if (score >= 90) return "var(--green)";
    if (score >= 60) return "#ca8a04";
    return "var(--red)";
  };

  return (
    <>
      <NavBar />
      <div style={{ background: "var(--white)", minHeight: "100vh", paddingTop: "120px", paddingBottom: "100px" }}>
        <div className="ui-wrap">
          
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: 24, marginBottom: 40, borderBottom: "1px solid var(--grey1)", paddingBottom: 24 }}>
            <div>
              <div style={{ fontFamily: "var(--fm)", fontSize: "10px", fontWeight: 700, color: "var(--red)", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 8 }}>
                SkyMind Core Pipeline Operations
              </div>
              <h1 style={{ fontFamily: "var(--fd)", fontSize: "clamp(2rem, 5vw, 4rem)", margin: 0, textTransform: "uppercase", letterSpacing: "-0.02em" }}>
                Pipeline <span style={{ color: "var(--red)" }}>Health.</span>
              </h1>
            </div>
            <div>
              <button onClick={loadDashboard} className="ui-btn ui-btn-black" style={{ height: 44 }}>
                Refresh Audit
              </button>
            </div>
          </div>

          {loading && (
            <div className="ui-card" style={{ padding: "80px 24px", textAlign: "center" }}>
              <div className="status-dot pulse" style={{ width: 16, height: 16, margin: "0 auto 24px" }} />
              <div style={{ fontFamily: "var(--fd)", fontSize: "1.5rem", color: "var(--black)" }}>LOADING PIPELINE DIAGNOSTICS...</div>
            </div>
          )}

          {error && (
            <div className="ui-card" style={{ padding: 40, borderColor: "var(--red)", background: "rgba(224,49,49,0.02)" }}>
              <div style={{ fontFamily: "var(--fb)", fontSize: "11px", fontWeight: 700, color: "var(--red)", textTransform: "uppercase", marginBottom: 12 }}>
                Audit Retrieve Failed
              </div>
              <div style={{ fontSize: "1rem", color: "var(--black)", marginBottom: 20 }}>
                {error}
              </div>
              <p style={{ fontSize: "0.85rem", color: "var(--grey3)", maxWidth: 500 }}>
                Make sure the validation reports are generated by executing the backend validator script:
                <code style={{ display: "block", background: "var(--off)", padding: 12, borderRadius: 8, marginTop: 8, fontFamily: "var(--fm)" }}>
                  python backend/tools/run_validation_dashboard.py
                </code>
              </p>
            </div>
          )}

          {report && !loading && (
            <div style={{ display: "grid", gridTemplateColumns: "1fr 340px", gap: 48, alignItems: "start" }}>
              {/* Checks list */}
              <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
                
                {[
                  { key: "chronology", name: "Chronology Validation", desc: "Verifies correct date ordering and absence of timestamp overlaps.", data: report.chronology },
                  { key: "duplicates", name: "Duplicates Audit", desc: "Tracks duplicates removed during ingestion batches and retention ratios.", data: report.duplicates },
                  { key: "leakage", name: "Target Leakage Protection", desc: "Performs mask-based backtests to ensure feature calculations have zero future visibility.", data: report.leakage },
                  { key: "health", name: "Booking Curve Integrity", desc: "Checks for singleton curves, curve sizes distribution, and isolation metrics.", data: report.health },
                  { key: "coverage", name: "Feature Coverage Diagnostics", desc: "Flags NaN coverage anomalies and identifies constant or zero-variance features.", data: report.coverage },
                  { key: "target_quality", name: "Supervised Target Quality", desc: "Ensures targets contain no corrupt values, negative fares, or missing horizons.", data: report.target_quality },
                  { key: "drift", name: "Feature Drift Detection", desc: "Calculates variance collapse and drift by comparing current stats against validation history.", data: report.drift },
                ].map((item) => (
                  <div key={item.key} className="ui-card" style={{ padding: 24, background: "var(--white)" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, marginBottom: 12 }}>
                      <div>
                        <h3 style={{ fontFamily: "var(--fd)", fontSize: "1.2rem", margin: 0 }}>{item.name}</h3>
                        <p style={{ fontSize: "0.8rem", color: "var(--grey3)", margin: "4px 0 0" }}>{item.desc}</p>
                      </div>
                      {getStatusBadge(item.data.status)}
                    </div>

                    {/* Warnings & Errors details */}
                    {(item.data.warnings?.length > 0 || item.data.errors?.length > 0) && (
                      <div style={{ marginTop: 16, borderTop: "1px solid var(--grey1)", paddingTop: 16, display: "flex", flexDirection: "column", gap: 12 }}>
                        {item.data.errors.map((err: string, i: number) => (
                          <div key={i} style={{ display: "flex", gap: 8, fontSize: "0.8rem", color: "var(--red)", fontWeight: 500 }}>
                            <span>❌</span>
                            <span>{err}</span>
                          </div>
                        ))}
                        {item.data.warnings.map((warn: string, i: number) => (
                          <div key={i} style={{ display: "flex", gap: 8, fontSize: "0.8rem", color: "#ca8a04", fontWeight: 500 }}>
                            <span>⚠️</span>
                            <span>{warn}</span>
                          </div>
                        ))}
                      </div>
                    )}

                    {/* Check statistics/metrics */}
                    {item.data.metrics && Object.keys(item.data.metrics).length > 0 && (
                      <div style={{ marginTop: 16, background: "var(--off)", padding: 12, borderRadius: 8 }}>
                        <div style={{ fontFamily: "var(--fb)", fontSize: "8px", color: "var(--grey3)", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 6 }}>
                          Associated Metrics
                        </div>
                        <div style={{ display: "flex", flexWrap: "wrap", gap: 16 }}>
                          {Object.entries(item.data.metrics).map(([k, v]: [string, any]) => {
                            if (typeof v === "object" || Array.isArray(v)) return null;
                            return (
                              <div key={k} style={{ fontSize: "0.75rem", fontFamily: "var(--fm)" }}>
                                <span style={{ color: "var(--grey3)" }}>{k}:</span>{" "}
                                <span style={{ color: "var(--black)", fontWeight: 600 }}>{String(v)}</span>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    )}

                  </div>
                ))}

              </div>

              {/* Sidebar score & history */}
              <div style={{ position: "sticky", top: 120, display: "flex", flexDirection: "column", gap: 24 }}>
                
                {/* Readiness Card */}
                <div className="ui-card" style={{ padding: 28, textAlign: "center", background: "var(--off)" }}>
                  <div style={{ fontFamily: "var(--fb)", fontSize: "10px", fontWeight: 700, color: "var(--grey3)", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 16 }}>
                    Global Pipeline Readiness
                  </div>
                  <div 
                    style={{ 
                      fontSize: "4.5rem", 
                      fontFamily: "var(--fd)", 
                      lineHeight: 1, 
                      color: getScoreColor(report.readiness_score),
                      marginBottom: 8 
                    }}
                  >
                    {report.readiness_score}%
                  </div>
                  <div style={{ fontSize: "11px", color: "var(--grey4)", fontWeight: 500 }}>
                    Overall pipeline status:{" "}
                    <span style={{ color: getScoreColor(report.readiness_score), fontWeight: 700 }}>
                      {report.overall_status}
                    </span>
                  </div>
                </div>

                {/* Audit Run Info */}
                <div className="ui-card" style={{ padding: 24 }}>
                  <div style={{ fontFamily: "var(--fb)", fontSize: "9px", fontWeight: 700, color: "var(--grey3)", textTransform: "uppercase", marginBottom: 12 }}>
                    Report Metadata
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 8, fontSize: "0.8rem", color: "var(--grey4)" }}>
                    <div>
                      <span style={{ color: "var(--grey3)" }}>Timestamp:</span><br />
                      <span style={{ fontFamily: "var(--fm)" }}>{new Date(report.timestamp).toLocaleString("en-IN")}</span>
                    </div>
                    <div>
                      <span style={{ color: "var(--grey3)" }}>Feature Schema:</span><br />
                      <span style={{ fontFamily: "var(--fm)" }}>{report.feature_set_version}</span>
                    </div>
                  </div>
                </div>

                {/* Validation History list */}
                {history.length > 0 && (
                  <div className="ui-card" style={{ padding: 24 }}>
                    <div style={{ fontFamily: "var(--fb)", fontSize: "9px", fontWeight: 700, color: "var(--grey3)", textTransform: "uppercase", marginBottom: 16 }}>
                      Audit History List
                    </div>
                    <div style={{ display: "flex", flexDirection: "column", gap: 12, maxHeight: 200, overflowY: "auto" }}>
                      {history.map((run, idx) => {
                        const isCurrent = run.timestamp === report.timestamp;
                        return (
                          <div 
                            key={idx}
                            onClick={() => loadHistoricalReport(run.timestamp)}
                            style={{ 
                              padding: 8, 
                              borderRadius: 8, 
                              border: isCurrent ? "1px solid var(--red)" : "1px solid var(--grey1)",
                              background: isCurrent ? "rgba(224,49,49,0.02)" : "var(--white)",
                              cursor: "pointer",
                              fontSize: "0.75rem"
                            }}
                          >
                            <div style={{ fontWeight: 600, color: isCurrent ? "var(--red)" : "var(--black)" }}>
                              Score: {run.readiness_score}% ({run.overall_status})
                            </div>
                            <div style={{ fontSize: "10px", color: "var(--grey3)", marginTop: 2 }}>
                              {new Date(run.timestamp).toLocaleString("en-IN")}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

              </div>
            </div>
          )}

        </div>
      </div>
    </>
  );
}
