"""
SkyMind — PDF Ticket Generation Service
Generates cinematic, noir-style boarding passes.
"""

from fpdf import FPDF
import os
from datetime import datetime

class TicketPDF(FPDF):
    def header(self):
        # Top-right corner tag
        if self.page_no() == 1:
            self.set_font("Courier", "B", 8)
            self.set_text_color(224, 49, 49)  # Red
            self.set_xy(self.w - 50, 5)
            self.cell(40, 10, "SKY-INTEL v4 // CONFIRMED", align="R")

    def footer(self):
        # Aesthetic barcode pattern at the bottom
        self.set_y(-25)
        self.set_fill_color(40, 40, 40)
        x_pos = 15
        while x_pos < self.w - 15:
            # Random-ish widths for barcode look
            width = 1.0 if (x_pos * 10) % 7 == 0 else 1.5
            if (x_pos * 10) % 13 == 0: width = 2.5
            self.rect(x_pos, self.h - 20, width, 8, "F")
            x_pos += width + 1.2
            
        self.set_y(-12)
        self.set_font("Courier", "B", 7)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"GENERATED BY SKYMIND CORE // {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} // SECURE TOKEN: {os.urandom(4).hex().upper()}", align="C")

def generate_ticket_pdf(data: dict) -> bytes:
    """
    Generate a Noir-themed PDF ticket.
    Expects: name, booking_ref, origin, destination, departure_date, amount, cabin
    """
    # Create PDF (A5 format is great for tickets)
    pdf = TicketPDF(orientation="P", unit="mm", format="A5")
    pdf.add_page()
    
    # 1. Background (Noir Dark)
    pdf.set_fill_color(11, 12, 13) # Noir Off
    pdf.rect(0, 0, pdf.w, pdf.h, "F")
    
    # 2. Main Header Block
    pdf.set_fill_color(26, 27, 30) # Card BG
    pdf.rect(0, 0, pdf.w, 45, "F")
    
    # SkyMind Logo/Text
    pdf.set_xy(12, 15)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, "SKYMIND", ln=True)
    
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(224, 49, 49) # Red
    pdf.set_x(12)
    pdf.cell(0, 5, "AI-POWERED TRAVEL INFRASTRUCTURE", ln=True)
    
    # Reference Tag
    pdf.set_fill_color(224, 49, 49)
    pdf.rect(pdf.w - 45, 18, 45, 12, "F")
    pdf.set_xy(pdf.w - 45, 18)
    pdf.set_font("Courier", "B", 14)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(45, 12, data.get("booking_ref", "------"), align="C")

    # 3. Journey Details
    pdf.set_xy(12, 60)
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(255, 255, 255)
    
    # Route: DEL > BOM
    route_text = f"{data.get('origin', '---')} > {data.get('destination', '---')}"
    pdf.cell(0, 15, route_text, ln=True)
    
    pdf.set_font("Courier", "B", 10)
    pdf.set_text_color(224, 49, 49)
    pdf.cell(0, 10, "BOARDING PASS / FLIGHT MANIFEST", ln=True)

    # 4. Details Grid
    pdf.ln(8)
    pdf.set_draw_color(44, 46, 51) # Border
    pdf.line(12, pdf.get_y(), pdf.w - 12, pdf.get_y())
    pdf.ln(6)

    # Column Headings
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(173, 181, 189) # Grey 3
    pdf.cell(40, 5, "PASSENGER NAME")
    pdf.cell(40, 5, "DEPARTURE DATE")
    pdf.cell(40, 5, "CABIN CLASS", ln=True)

    # Column Values
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(40, 10, data.get("name", "TRAVELLER").upper())
    pdf.cell(40, 10, data.get("departure_date", "TBD"))
    pdf.cell(40, 10, data.get("cabin", "ECONOMY").upper(), ln=True)

    pdf.ln(4)
    pdf.line(12, pdf.get_y(), pdf.w - 12, pdf.get_y())
    pdf.ln(6)

    # Row 2 Headings
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(173, 181, 189)
    pdf.cell(40, 5, "TOTAL FARE")
    pdf.cell(40, 5, "TICKET STATUS")
    pdf.cell(40, 5, "BOARDING GATE", ln=True)

    # Row 2 Values
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(40, 10, data.get("amount", "INR 0.00"))
    
    # Status highlight
    pdf.set_text_color(43, 138, 62) # Green
    pdf.cell(40, 10, "VERIFIED")
    
    pdf.set_text_color(255, 255, 255)
    pdf.cell(40, 10, "SEE DASHBOARD", ln=True)

    # 5. Security & Instructions
    pdf.set_xy(12, pdf.h - 70)
    pdf.set_fill_color(20, 21, 23)
    pdf.rect(12, pdf.get_y(), pdf.w - 24, 30, "F")
    
    pdf.set_xy(16, pdf.get_y() + 5)
    pdf.set_font("Courier", "I", 8)
    pdf.set_text_color(173, 181, 189)
    pdf.multi_cell(pdf.w - 32, 5, "SECURITY NOTICE: This document is a valid digital confirmation of your booking. Please carry a government-issued photo ID for airport entry. Web check-in opens 48 hours prior to departure.")

    # 6. Return as bytes
    return pdf.output()
